[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "src",
]

[tool.coverage.run]
source = [
    "mtd_sync",
]
omit = [
    "*/tests/*",
    "*/migrations/*",
]

[tool.black]
line-length = 99
