query getDossier(
  $dossierNumber: Int!
  $includeChamps: Boolean = true
  $includeAnotations: Boolean = true
) {
  dossier(number: $dossierNumber) {
    ...DossierFragment
  }
}

fragment DossierFragment on Dossier {
  __typename
  id
  number
  state

  champs @include(if: $includeChamps) {
    ...ChampFragment
    ...RootChampFragment
  }
  annotations @include(if: $includeAnotations) {
    ...ChampFragment
    ...RootChampFragment
  }
}

fragment RootChampFragment on Champ {
  ... on RepetitionChamp {
    rows {
      champs {
        ...ChampFragment
      }
    }
  }
  ... on DossierLinkChamp {
    dossier {
      id
      number
      state
    }
  }
}

fragment ChampFragment on Champ {
  id
  champDescriptorId
  __typename
  label
  stringValue
  prefilled
  columns {
    ...ColumnFragment
  }
  ... on DateChamp {
    date
  }
  ... on DatetimeChamp {
    datetime
  }
  ... on CheckboxChamp {
    checked: value
  }
  ... on YesNoChamp {
    selected: value
  }
  ... on DecimalNumberChamp {
    decimalNumber: value
  }
  ... on IntegerNumberChamp {
    integerNumber: value
  }
  ... on CiviliteChamp {
    civilite: value
  }
  ... on LinkedDropDownListChamp {
    primaryValue
    secondaryValue
  }
  ... on MultipleDropDownListChamp {
    values
  }
}

fragment FileFragment on File {
  __typename
  filename
  contentType
  checksum
  byteSize: byteSizeBigInt
  url
  createdAt
}

fragment ColumnFragment on Column {
  __typename
  id
  label
  ... on TextColumn {
    textValue: value
  }
  ... on BooleanColumn {
    booleanValue: value
  }
  ... on DateColumn {
    dateValue: value
  }
  ... on DateTimeColumn {
    dateTimeValue: value
  }
  ... on IntegerColumn {
    integerValue: value
  }
  ... on DecimalColumn {
    decimalValue: value
  }
  ... on EnumColumn {
    enumValue: value
  }
  ... on EnumsColumn {
    enumsValue: value
  }
  ... on AttachmentsColumn {
    attachmentsValue: value {
      ...FileFragment
    }
  }
}